### ISSUE TITLE
Servicecomb.Saga.Omega.Protocol报错

### ISSUE THREAD

**Issue by minlong331** [OpenSagas-csharp/servicecomb-saga-csharp#9]
我想问
Servicecomb.Saga.Omega.Protocol.GrpcTxEvent.cs 里面的
`
    public const int GlobalTxIdFieldNumber = 2;
    private string globalTxId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GlobalTxId {
      get { return globalTxId_; }
      set {
        globalTxId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }`
在set的时候报错了，value是null，这是啥问题呢？

**Comment by withlin** [comment]
Can you describe how you are running?
